export const emptyAsset = {
  assetTag: "",
  category: "Laptop",
  description: "",
  manufacturer: "",
  model: "",
  serialNumber: "",
  purchaseDate: "",
  inServiceDate: "",
  purchaseValue: "",
  salvageValue: "0.00",
  usefulLifeMonths: 48,
  department: "",
  location: "",
  assignedUserId: "",
  condition: "Good",
  status: "Available",
  imageKey: "",
};
